# any of the conditions below match
type = "or"
conditions = [
    
    {type = "whitelist", kind = "owner", agents = ["030c8f9c4dc0b8f3c006fa85a47c9156dedbede000a8b764c6e374fd097e873ba04"]},
    {type = "whitelist", kind = "owner", agents = ["0216133993bbc54c0d48a21634a7d2632b8c92d744d565839dc39c912ef406e0d93"]}
]
# evaluates to always false as both public keys are 67 charaters (base16) which is invalid
# this is done as a safety check so that nobody uses these predicates by mistake 
